### ISSUE TITLE
Mapping FPDS Set-Asides to USA Spending Set-Asides

### ISSUE THREAD

**Issue by fedspend123** [fedspendingtransparency/usaspending-website#1730]
**FPDS Set-Asides:**

1. Small Business Actions
2. Small Business Dollars
3. Small Disadvantaged Business Dollars
4. 8(a) Procedure Dollars
5. Veteran Owned Small Business Dollars
6. Service Disabled Veteran Owned Small Business Dollars
7. Women Owned Small Business Dollars
8. Certified HUBZone Small Business Dollars

**USA Spending Set-Asides:**

1. 8(A) SOLE SOURCE
2. 8A COMPETED
3. BUY INDIAN
4. ECONOMICALLY DISADVANTAGED WOMEN OWNED SMALL BUSINESS
5. ECONOMICALLY DISADVANTAGED WOMEN OWNED SMALL BUSINESS SOLE SOURCE
6. HUBZONE SET-ASIDE
7. HUBZONE SOLE SOURCE
8. INDIAN ECONOMIC ENTERPRISE
9. RESERVED FOR SMALL BUSINESS
10. SDVOSB SOLE SOURCE
11. SERVICE DISABLED VETERAN OWNED SMALL BUSINESS SET-ASIDE
12. SMALL BUSINESS SET ASIDE - PARTIAL
13. SMALL BUSINESS SET ASIDE - TOTAL
14. WOMEN OWNED SMALL BUSINESS
15. WOMEN OWNED SMALL BUSINESS SOLE SOURCE
16. NO SET ASIDE USED.
17. N/A

Thanks!

**Comment by lisaam** [comment]
"Would the numbers be more relatable if displayed in terms of dollars per paycheck? #1687"
Interesting idea. We can suggest this are story for the Data Lab to look at.

**Comment by fedspend123** [comment]
@lisaam "We can suggest this are story for the Data Lab to look at." -- yes, can you please?

**Comment by fedspend123** [comment]
@lisaam  Sorry to keep bugging you on this -- can you help w/ this request?

**Comment by lisaam** [comment]
@fedspend123  I'll be happy to help. I already answered your question about dollars per paycheck. Do you have a different question?

**Comment by SaavyGirl** [comment]
Looks goog

**Comment by SaavyGirl** [comment]
[src]()
