### ISSUE TITLE
For Place of Performance, summary pages are showing US state codes when country is non-US

### ISSUE THREAD

**Issue by geoffgeiling** [fedspendingtransparency/usaspending-website#191]
On the award summary pages, the Place of Performance is showing a US state code when the country is non-US. 

After surveying 50+ records, instance is occurring 100% of the time.

i.e. 
VA, Canada
NY, Iraq
NC, Paraguay

![screen shot 2017-05-04 at 10 10 25 am](https://cloud.githubusercontent.com/assets/19841060/25707586/06b97b1c-30b2-11e7-9faa-bcd5e25939ae.png)

**Comment by rmaziarz** [comment]
fixed this bug: 
![image](https://user-images.githubusercontent.com/8397754/28700304-dedeedb8-731c-11e7-8fbc-93e2e8dce777.png)
