### ISSUE TITLE
Confusion between Spending by Award - Funding Agency and Awarding Agency search page and individual award page

### ISSUE THREAD

**Issue by lauraGgit** [fedspendingtransparency/usaspending-website#194]
On the [https://spendingdata.us/#/search] page the IND17PD00420 displays the funding agency by default but on the [individual award page](https://spendingdata.us/#/award/728263) it shows the awarding agency first, which the funding agency in a drop down, which at first was a little confusing.

![image](https://cloud.githubusercontent.com/assets/5840989/25719150/6d68b7e6-30d6-11e7-8c79-4992a9ddad6a.png)

![image](https://cloud.githubusercontent.com/assets/5840989/25719172/81b6222e-30d6-11e7-8c9c-bdc867513dba.png)

**Comment by geoffgeiling** [comment]
Hi Laura, thanks for the comment! We have a story in the backlog to address changing to Awarding Agency to be the default across both pages.
https://federal-spending-transparency.atlassian.net/browse/DS-1211
