### ISSUE TITLE
Enhancement: Clickable Budget Categories

### ISSUE THREAD

**Issue by lauraGgit** [fedspendingtransparency/usaspending-website#195]
I would love to be able to drill down on the individual budget categories here.
![image](https://cloud.githubusercontent.com/assets/5840989/25719298/f646067c-30d6-11e7-8cf5-28745e16f6fb.png)

**Comment by geoffgeiling** [comment]
Laura, that's a great idea and one we've considered. I'm curious, what would you expect to see in the next level?

**Comment by lauraGgit** [comment]
I think either by agency or the Federal Accounts.
