### ISSUE TITLE
Unable to see the search filters when viewing the site on an iPhone

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/usaspending-website#196]
I'm not sure if this is specific to iPhones or impacts other mobile devices, but the left-hand filters on the search search don't appear when I views the site there. Otherwise, it looks great!

**Comment by kaitlin** [comment]
We have an issue to track this, it will likely be in the next sprint (starting 5/10):
https://federal-spending-transparency.atlassian.net/browse/DS-1056
