### ISSUE TITLE
Searching on "FL, State in US" returns different results than "Florida, State in US"

### ISSUE THREAD

**Issue by kaitlin** [fedspendingtransparency/usaspending-website#197]
I can only find this [contract](https://spendingdata.us/#/award/11245) in the search when using `recipient location = FL, State in US` but not when searching `recipient location = Florida, State in US`.

**Comment by bsweger** [comment]
Thanks for the report. We're aware of the issue and have an open story in our backlog to address it: https://federal-spending-transparency.atlassian.net/browse/DS-1047
