### ISSUE TITLE
Unable to click federal accounts links

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/usaspending-website#198]
On an iPhone, when viewing the _Spending by:_ bar chart on the search page, the hyperlinks to federal accounts don't work. They look like links, and the page sort of blinks when you press them, but nothing happens.

![file](https://cloud.githubusercontent.com/assets/540544/25722747/4885765a-30e3-11e7-9459-b03e75594a36.jpeg)

**Comment by geoffgeiling** [comment]
This appears to also be the case in Safari
