### ISSUE TITLE
When I check "all fiscal years" only 2017 data displays to me

### ISSUE THREAD

**Issue by wslack** [fedspendingtransparency/usaspending-website#224]
This is confusing since I would assume that checking the boxes for all of the available fiscal years would get me a graph over time. Also, the API returned fairly slowly when I checked the box, possibly because traffic is high right now.

**Comment by bsweger** [comment]
Thanks for the repot @wslack! The first DATA Act reporting period was Q2 2017, so that's why you only see 2017 data on the site right now. We'll be loading in awards data from the current usaspending.gov throughout the summer.

**Comment by wslack** [comment]
That makes sense! I think users of the beta might be confused, but its a beta so it shouldn't be a big problem. Want me to close?

**Comment by wslack** [comment]
Filed to be clear about this: https://github.com/fedspendingtransparency/usaspending-website/pull/227
