### ISSUE TITLE
Mobile users can't scroll below map on homepage

### ISSUE THREAD

**Issue by andrewmaier** [fedspendingtransparency/usaspending-website#225]
The map on the homepage is full width and taller than the screen on my iPhone, which means I can't pan down and see the footer. :( (This screenshot is from my desktop.)

![image](https://cloud.githubusercontent.com/assets/2970/25858354/8e97e21c-34a9-11e7-911c-a78d25902955.png)

**Comment by laurenancona** [comment]
Hopefully this might save some time - 
the current [recommended](https://github.com/mapbox/mapbox-gl-js/issues/4297) way to account for this in the GL API is to detect mobile and [disable the `dragRotateHandler`](https://www.mapbox.com/mapbox-gl-js/api/#dragrotatehandler) if `mobile` = `true`.

**Comment by mab6bf** [comment]
Thanks for the suggestion, @laurenancona! We're implementing that suggestion this sprint, along with mobile-only buttons that pan the map up, down, left, and right.
