### ISSUE TITLE
spending-api.us DNS Issue

### ISSUE THREAD

**Issue by blackstarhero** [fedspendingtransparency/usaspending-website#229]
Link is not resolving for https://spending-api.us/docs/data-dictionary

See blank entry for A record below 

;; QUESTION SECTION:
;spending-api.us.		IN	A

;; AUTHORITY SECTION:
spending-api.us.	880	IN	SOA	ns-1596.awsdns-07.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

**Comment by kaitlin** [comment]
Ah yes, we're in the process of setting up redirects from the old domain to the new one we launched today. You can find the docs here:
https://api.usaspending.gov/docs/data-dictionary

Where did you find the link? I'd like to go clean up any hanging references.
