### ISSUE TITLE
![image](https://user-images.githubusercontent.com/81043541/112047190-5587a000-8b23-11eb-856c-a5aa06fd6cab.png)

### ISSUE THREAD

**Issue by badassconnection** [fedspendingtransparency/usaspending-website#2469]
![image](https://user-images.githubusercontent.com/81043541/112047190-5587a000-8b23-11eb-856c-a5aa06fd6cab.png)

__Originally posted by @badassconnection in https://github.com/fedspendingtransparency/usaspending-website/pull/2466#discussion_r599015087__

**Comment by tony-sappe** [comment]
spam
