### ISSUE TITLE
Invalid Congressional District

### ISSUE THREAD

**Issue by DATAActTeam** [fedspendingtransparency/usaspending-website#2577]
1.	Per current requirements outlined in the Practices and Procedures (https://community.max.gov/download/attachments/754091528/Practices-and-Procedures-v2.0.pdf?api=v2), reporting agency must enter 9-digit zip code into the PrimaryPlaceOfPerformanceZIP+4 field (where applicable), and the USASpending automatically assigns the PrimaryPlaceOfPerformanceCongressionalDistrict
a.	In other words, the reporting agency leaves the PrimaryPlaceOfPerformanceCongressionalDistrict blank anytime there is a PrimaryPlaceOfPerformanceZIP+4 available 
2.	For FAIN DTNH2217H00135, mod # 0005, we entered PrimaryPlaceOfPerformanceZIP+4 787012409 and left the PrimaryPlaceOfPerformanceCongressionalDistrict blank
3.	We went to the US House of Representatives website (https://www.house.gov/representatives/find-your-representative), entered 787012409 into the tool, and arrived at Congressional District # 25
4.	However, the USASpending automatically assigned PrimaryPlaceOfPerformanceCongressionalDistrict # 21
5.	This leads us to conclude that USASpending assigned PrimaryPlaceOfPerformanceCongressionalDistrict # 21 as an error because it should have been # 25

For more information, please see attached screenshots.

Please help us understand why there is a discrepancy.
[Congressional District.docx](https://github.com/fedspendingtransparency/usaspending-website/files/6517393/Congressional.District.docx)

**Comment by lisaam** [comment]
Hi,

Please submit this issue to the USAspending Service Desk by sending an email to USAspending.help@fiscal.treasury.gov from a .gov or .mil email address. Please include the submission ID where this is occurring. 

Thanks!
