### ISSUE TITLE
RDS Snapshot Not Exposed to US-GOV-WEST-1

### ISSUE THREAD

**Issue by morgans2** [fedspendingtransparency/usaspending-website#834]
The USAspending.gov dataset is available in us-east-1, but not available in us-gov-west-1. We primarily work in govcloud and will need to probably come up with a convoluted workaround to pull the data into us-gov-west-1 or mature our pull from the website itself. 

Is there any plan to expose the dataset into govcloud?

**Comment by lisaam** [comment]
The full USAspending.gov PostgreSQL Database Download is available at http://usaspending-db.s3-website-us-gov-west-1.amazonaws.com/

**Comment by morgans2** [comment]
Thank you!! I'll be testing this out this week!

**Comment by morgans2** [comment]
We have confirmed with our own customer that we will need to keep this data as current as possible. Is it possible to have it refreshed to GOV-WEST on a regular basis?

**Comment by lisaam** [comment]
Our database download at https://files.usaspending.gov/database_download/ is updated monthly.
