### ISSUE TITLE
Can not find Snapshots on AWS

### ISSUE THREAD

**Issue by ornichamagic** [fedspendingtransparency/usaspending-website#995]
![screen shot 2562-01-17 at 20 48 40](https://user-images.githubusercontent.com/12793552/51360483-dd804400-1a99-11e9-870a-caaff8f8302d.png)

I've already changed region to US East (N. Virginia), and I still cannot search "515495268755".

https://docs.opendata.aws/usaspending/readme.html

**Comment by bezdomny** [comment]
same here. any word on this?

**Comment by rdg7739** [comment]
Same here. Seems like no one is checking this...

**Comment by mrgoynes** [comment]
Bump.

**Comment by xenvya** [comment]
bump.  any updates?

**Comment by rdg7739** [comment]
They Don’t support anymore. You have to use the full DB from their website
